name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

  # Make a latest update build to keep things in shape
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * 0

jobs:

  build_images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:

          # The docker_target is a stage within the multistage pipeline
          # The tag is what we push to dockerhub under the hamletio/hamlet image

          - docker_target: hamlet
            suffix: ''
          - docker_target: jenkins-jnlp-agent
            suffix: -jenkins
          - docker_target: azure-pipelines-agent
            suffix: -azpipeline

          - docker_target: meteor-hamlet
            suffix: -builder-meteor
          - docker_target: meteor-jenkins-jnlp-agent
            suffix: -jenkins-builder-meteor
          - docker_target: meteor-azure-pipelines-agent
            suffix: -azpipeline-builder-meteor

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{github.repository}}
          flavor: |
            latest=auto
            suffix=${{ matrix.suffix }}
          tags: |
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=schedule,pattern=nightly
            type=schedule,pattern=schedule-{{date 'YYYYMMDD'}}
            type=sha

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Release
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'scheduled' || startsWith(github.ref, 'refs/tags/*') || github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.docker_target }}
          build-args: |
            engine=${{steps.pick_engine.outputs.engine}}
